#ifndef __STATUS_CODE_H__
#define __STATUS_CODE_H__


typedef enum _CHTTPSERVER_STATUS_CODE {
    CHTTPSERVER_STATUS_CODE_CONTINUE = 100,
    CHTTPSERVER_STATUS_CODE_SWITCHING_PROTOCOLS = 101,
    CHTTPSERVER_STATUS_CODE_OK = 200,
    CHTTPSERVER_STATUS_CODE_CREATED = 201,
    CHTTPSERVER_STATUS_CODE_ACCEPTED = 202,
    CHTTPSERVER_STATUS_CODE_NON_AUTHORITATIVE_INFORMATION = 203,
    CHTTPSERVER_STATUS_CODE_NO_CONTENT = 204,
    CHTTPSERVER_STATUS_CODE_RESET_CONTENT = 205,
    CHTTPSERVER_STATUS_CODE_PARTIAL_CONTENT = 206,
    CHTTPSERVER_STATUS_CODE_MULTIPLE_CHOICES = 300,
    CHTTPSERVER_STATUS_CODE_MOVED_PERMANENTLY = 301,
    CHTTPSERVER_STATUS_CODE_FOUND = 302,
    CHTTPSERVER_STATUS_CODE_SEE_OTHER = 303,
    CHTTPSERVER_STATUS_CODE_NOT_MODIFIED = 304,
    CHTTPSERVER_STATUS_CODE_USE_PROXY = 305,
    CHTTPSERVER_STATUS_CODE_UNUSED = 306,
    CHTTPSERVER_STATUS_CODE_TEMPORARY_REDIRECT = 307,
    CHTTPSERVER_STATUS_CODE_BAD_REQUEST = 400,
    CHTTPSERVER_STATUS_CODE_UNAUTHORIZED = 401,
    CHTTPSERVER_STATUS_CODE_PAYMENT_REQUIRED = 402,
    CHTTPSERVER_STATUS_CODE_FORBIDDEN = 403,
    CHTTPSERVER_STATUS_CODE_NOT_FOUND = 404,
    CHTTPSERVER_STATUS_CODE_METHOD_NOT_ALLOWED = 405,
    CHTTPSERVER_STATUS_CODE_NOT_ACCEPTABLE = 406,
    CHTTPSERVER_STATUS_CODE_PROXY_AUTHENTICATION_REQUIRED = 407,
    CHTTPSERVER_STATUS_CODE_REQUEST_TIMEOUT = 408,
    CHTTPSERVER_STATUS_CODE_CONFLICT = 409,
    CHTTPSERVER_STATUS_CODE_GONE = 410,
    CHTTPSERVER_STATUS_CODE_LENGTH_REQUIRED = 411,
    CHTTPSERVER_STATUS_CODE_PRECONDITION_FAILED = 412,
    CHTTPSERVER_STATUS_CODE_REQUEST_ENTITY_TOO_LARGE = 413,
    CHTTPSERVER_STATUS_CODE_REQUEST_URI_TOO_LONG = 414,
    CHTTPSERVER_STATUS_CODE_UNSUPPORTED_MEDIA_TYPE = 415,
    CHTTPSERVER_STATUS_CODE_REQUESTED_RANGE_NOT_SATISFIABLE = 416,
    CHTTPSERVER_STATUS_CODE_EXPECTATION_FAILED = 417,
    CHTTPSERVER_STATUS_CODE_INTERNAL_SERVER_ERROR = 500,
    CHTTPSERVER_STATUS_CODE_NOT_IMPLEMENTED = 501,
    CHTTPSERVER_STATUS_CODE_BAD_GATEWAY = 502,
    CHTTPSERVER_STATUS_CODE_SERVICE_UNAVAILABLE = 503,
    CHTTPSERVER_STATUS_CODE_GATEWAY_TIMEOUT = 504,
    CHTTPSERVER_STATUS_CODE_HTTP_VERSION_NOT_SUPPORTED = 505,
} CHTTPSERVER_STATUS_CODE;


#ifdef __cplusplus
extern "C" {
#endif

    extern const char * chttpserver_status_get_message(int code);

#ifdef __cplusplus
}
#endif

#endif /* __STATUS_CODE_H__ */
